create table public.deployments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  wallet_address text not null,
  node_count integer not null,
  amount_sol numeric not null,
  transaction_signature text not null,
  constraint deployments_pkey primary key (id)
);
