import React from 'react';
import { Calculator } from 'lucide-react';

interface EarningsCardProps {
    nodeCount: number;
    pricePerNode: number;
}

export const EarningsCard: React.FC<EarningsCardProps> = ({ nodeCount, pricePerNode }) => {
    // Assumptions based on prompt: "we pay them half the earnings"
    // Let's assume the $2056 is the cost, and the revenue is higher.
    // Prompt says: "pay $2056... we pay them half the earnings"
    // Let's assume the "earnings" means the revenue generated by the node.
    // If ROI is ~38% (from image), then Net Profit = Cost * 0.38
    // Net Profit = Revenue - Cost
    // Wait, "we pay them half the earnings". This might mean Revenue Share.
    // Let's stick to the visual reference which shows:
    // Cost: -$2056
    // Net Profit: +$794
    // Revenue: $2850
    // So Revenue = Cost + Net Profit = 2056 + 794 = 2850.
    // And 794 / 2056 ~= 38.6% ROI.

    const revenuePerNode = 3591.6; // 119.72 * 30
    const costPerNode = pricePerNode;

    const totalRevenue = revenuePerNode * nodeCount;
    const totalCost = costPerNode * nodeCount;
    const netProfit = totalRevenue - totalCost;
    const dailyYield = totalRevenue / 30;
    const roi = (netProfit / totalCost) * 100;

    return (
        <div className="glass-panel" style={{ padding: '2rem', height: '100%' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '2rem' }}>
                <Calculator size={24} color="#10b981" />
                <h2 style={{ fontSize: '1.25rem', fontWeight: 'bold' }}>Projected Earnings</h2>
            </div>

            <div style={{ marginBottom: '2rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Est. Daily Yield</span>
                    <span style={{ color: 'white', fontWeight: '600' }}>${dailyYield.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                </div>
                <div style={{ height: '4px', background: 'rgba(255,255,255,0.1)', borderRadius: '2px', overflow: 'hidden' }}>
                    <div style={{ width: '100%', height: '100%', background: 'var(--accent)' }}></div>
                </div>
            </div>

            <div style={{
                background: 'rgba(255,255,255,0.03)',
                borderRadius: '12px',
                padding: '1.5rem',
                marginBottom: '2rem',
                border: '1px solid rgba(255,255,255,0.05)'
            }}>
                <div style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '0.5rem' }}>Est. 30-Day Revenue</div>
                <div style={{ fontSize: '2.5rem', fontWeight: 'bold', color: 'var(--accent)', marginBottom: '0.5rem' }}>
                    ${totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </div>
                <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>
                    Based on current A²E spot rates
                </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Deployment Cost:</span>
                    <span style={{ color: '#ef4444' }}>-${totalCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
                    <span style={{ color: 'var(--text-muted)' }}>Est. Net Profit:</span>
                    <span style={{ color: 'var(--accent)' }}>+${netProfit.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
                </div>
                <div style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    paddingTop: '1rem',
                    borderTop: '1px solid var(--border)',
                    alignItems: 'center'
                }}>
                    <span style={{ color: 'white', fontWeight: '600' }}>Est. ROI (30 Days):</span>
                    <span style={{ color: '#a78bfa', fontWeight: 'bold', fontSize: '1.1rem' }}>~{roi.toFixed(1)}%</span>
                </div>
            </div>

            <div style={{
                marginTop: '2rem',
                background: 'rgba(255, 165, 0, 0.1)',
                border: '1px solid rgba(255, 165, 0, 0.2)',
                borderRadius: '8px',
                padding: '1rem'
            }}>
                <p style={{ color: '#fbbf24', fontSize: '0.75rem', lineHeight: '1.4' }}>
                    <strong style={{ display: 'block', marginBottom: '0.25rem' }}>⚠ Alpha Disclaimer:</strong>
                    Figures are estimates based on current network demand and A²E arbitrage rates. Actual earnings may vary. No uptime guarantees apply and nodes may experience downtime during alphaTesting when updates or changes to the protocol are being made.
                </p>
            </div>
        </div>
    );
};
